Replace any occurence of yum-centos/yum-epel/yum-elrepo with osl-repos equivilents
osuosl-cookbooks/osl-scponly pull request #8
Opened 2021-01-13 21:31 UTC by TheREK3R

2021-01-21 01:32 UTC, ramereth requested changes

2021-01-21 01:32 UTC, ramereth commented on kitchen.dokken.yml
> +      pid_one_command: /usr/lib/systemd/systemd
Let's not add this yet

2021-01-21 01:32 UTC, ramereth commented on kitchen.dokken.yml
> +      pid_one_command: /usr/lib/systemd/systemd
Let's not add this yet

2021-01-21 02:10 UTC, TheREK3R commented on kitchen.dokken.yml
> +      pid_one_command: /usr/lib/systemd/systemd
removed

2021-01-25 21:06 UTC, ramereth commented
LGTM

2021-02-03 01:43 UTC, ramereth approved these changes
Please do a minor bump on `~`

2021-02-03 17:35 UTC, TheREK3R commented
!bump minor ~

2021-02-03 17:36 UTC, merged

2021-02-03 17:36 UTC, osuosl-manatee commented
Jenkins has merged this PR into `master` and has automatically performed a minor-level version bump to v1.3.0.  Have a nice day!